LOGIN_TEMPLATE = 'theme/account/login.html'
REGISTRATION_TEMPLATE = 'theme/account/signup.html'
FORGET_TEMPLATE = 'theme/account/forgot_password.html'
HOME_TEMPLATE = 'index.html'
ABOUT_TEMPLATE = 'theme/about_page.html'